// Embeds the YAML reference (split into agent-facing topics) and the example
// forms as importable string maps, so `yaml-form docs` / `example` work
// offline from an npx or single-binary install with no repo present.
// Regenerate with `bun run build:embedded` (also run by `bun run check`).
//
// Topics are keyed off `docs/reference.md` headings: if a heading is renamed
// or removed the build throws here rather than silently dropping a topic.

import { readdir } from "node:fs/promises";

interface Topic {
	slug: string;
	/** Exact heading line in reference.md that starts this topic's section. */
	heading: string;
}

// Order here is the order `yaml-form docs` lists topics in.
const TOPICS: Topic[] = [
	{ slug: "top-level", heading: "### Top level" },
	{ slug: "fields", heading: "### Common item fields" },
	{ slug: "items", heading: "### Item types" },
	{ slug: "answers", heading: "### Submitted data shape" },
	{ slug: "rules", heading: "### Conditional visibility (`visible_when`)" },
	{ slug: "prefill", heading: "### URL-parameter prefill" },
	{ slug: "draft", heading: "### Draft autosave" },
	{ slug: "i18n", heading: "### Language and UI strings (`lang`, `messages`)" },
	{ slug: "actions", heading: "### Actions" },
	{ slug: "payload", heading: "### Payload" },
];

const refPath = new URL("../docs/reference.md", import.meta.url).pathname;
const reference = await Bun.file(refPath).text();
const lines = reference.split("\n");

function extractSection(heading: string): string {
	const start = lines.indexOf(heading);
	if (start === -1) {
		throw new Error(
			`build-embedded: heading not found in docs/reference.md: ${heading}\n` +
				"Update TOPICS in scripts/build-embedded.ts to match the reference.",
		);
	}
	// A level 1–3 heading ends the section (level 4+ stays inside), but only
	// outside a fenced code block — a column-0 `#` in a YAML/shell example is
	// content, not a boundary.
	let end = start + 1;
	let inFence = false;
	for (; end < lines.length; end++) {
		const line = lines[end] as string;
		if (/^```/.test(line)) inFence = !inFence;
		else if (!inFence && /^#{1,3} /.test(line)) break;
	}
	return `${lines.slice(start, end).join("\n").trimEnd()}\n`;
}

const docs: Record<string, string> = {};
for (const topic of TOPICS) docs[topic.slug] = extractSection(topic.heading);

const examplesDir = new URL("../examples/", import.meta.url).pathname;
const examples: Record<string, string> = {};
for (const name of (await readdir(examplesDir)).sort()) {
	if (!name.endsWith(".yaml")) continue;
	const slug = name.replace(/\.yaml$/, "");
	examples[slug] = await Bun.file(`${examplesDir}${name}`).text();
}

const banner =
	"// Generated by `bun run build:embedded` — do not edit by hand.\n// biome-ignore-all lint: generated file\n";
const body =
	`export const docTopics: readonly string[] = ${JSON.stringify(TOPICS.map((t) => t.slug))};\n` +
	`export const docs: Record<string, string> = ${JSON.stringify(docs)};\n` +
	`export const examples: Record<string, string> = ${JSON.stringify(examples)};\n`;

const target = new URL("../src/embedded.generated.ts", import.meta.url)
	.pathname;
await Bun.write(target, `${banner}${body}`);
console.log(
	`wrote ${target} (${TOPICS.length} topics, ${Object.keys(examples).length} examples)`,
);
