// Bundles the browser runtime and writes it as an importable string module,
// so HTML generation needs no bundler at runtime (works under Node and in
// compiled binaries). Regenerate with `bun run build:runtime` (also run by
// `bun run check`).
const entry = new URL("../src/runtime/main.ts", import.meta.url).pathname;
const result = await Bun.build({
	entrypoints: [entry],
	target: "browser",
	minify: true,
});
const output = result.outputs[0];
if (!result.success || !output) {
	console.error(result.logs.join("\n"));
	process.exit(1);
}
const code = await output.text();
const target = new URL("../src/generate/runtime.generated.ts", import.meta.url)
	.pathname;
const banner =
	"// Generated by `bun run build:runtime` — do not edit by hand.\n// biome-ignore-all lint: generated file\n";
await Bun.write(
	target,
	`${banner}export const runtimeBundle: string = ${JSON.stringify(code)};\n`,
);
console.log(`wrote ${target} (${code.length} bytes of runtime)`);
